version: "3.7"
services:
  db:
    image: envirocar/vehicles-db:latest
    build: ./db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
  vehicles:
    image: envirocar/vehicles:latest
    build: .
    ports:
      - 8080:8080
    environment: 
      PORT: 8080
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_ADDR: db:5432
    depends_on: 
      - db
      
